env:
  browser: true
  es2019: true
extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:@stylistic/recommended-extends'
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - '@stylistic'
rules:
  '@stylistic/indent': ['error', 2]
  '@stylistic/quotes': ['error', 'single']
  '@stylistic/jsx-quotes': ['error', 'prefer-single']
  '@stylistic/semi': ['error', 'always']
  '@stylistic/member-delimiter-style': ['error', {
      multiline: {
        delimiter: 'semi',
        requireLast: true
      },
      singleline: {
        delimiter: 'semi',
        requireLast: false
      },
      multilineDetection: 'brackets',
    }]
  '@stylistic/arrow-parens': ['error', 'always']
  '@typescript-eslint/no-unused-vars': ['error', { argsIgnorePattern: '^_' }]
ignorePatterns:
  - 'node_modules/**'
  - 'dist/**'
  - 'ts-macros/**'
